import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased bg-lightest-beige`}>
        {children}
        <Script id="analytics-listener" strategy="afterInteractive">
          {`
            document.addEventListener("click", (event) => {
              const link = event.target.closest("a[data-analytics]");
              if (link) {
                const label = link.getAttribute("data-analytics");
                const href = link.getAttribute("href");

                fetch("http://localhost:8000/api/track", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({
                    type: "link_click",
                    label,
                    href,
                    timestamp: Date.now()
                  }),
                });
              }
            });
          `}
        </Script>
      </body>
    </html>
  );
}
